route:
  group_by: ["alertname", "job"]
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 30m
  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: discordwebhook.url.adresi
